---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  sonar-python:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - ucsmsdk/*.py
  - ucsmsdk/utils/*.py
exclude_paths:
- tests/
- docs/
- ucsmsdk/mometa/
- ucsmsdk/methodmeta/
- ucsmsdk/ucsmeta.py
- ucsmsdk/ucsconstants.py
- ucsmsdk/ucsfiltertype.py
- ucsmsdk/ucsbasetype.py
- ucsmsdk/ucsmethodfactory.py
